### ISSUE TITLE
Is there an example of an item with a card layout with multiple fields?

### ISSUE THREAD

**Issue by rouilj** [riktar/jkanban#106]
How would I create a kanban item with the following structure:
```
Title: Present delivery
Owner: rouilj  <avatar image of rouilj>
Due date: 2020-12-25
```

It looks like the title property is a single line text string. I can add the owner, dueDate
ownerAvatar as custom properties, but how do I get them displayed in the item/card?

Can the
```
customHandler       : "<span class='item_handle'>+</span> %s"// your entirely customized handler. Use %s to position item title
```
property be used in some way to format the item? I don't see any doc on the customHander but
I assume it is meant to provide a handle to click on to start drag and drop. Otherwise the whole item/card accepts a click to drag and drop.

**Comment by rbmcgowan** [comment]
@rouilj did you find anything on how to do this ?  I want to do the same, can't see any obvious way to do so

**Comment by rouilj** [comment]
Hi rbmcgowan:

In message <riktar/jkanban/issues/106/740419591@github.com>,
rbmcgowan writes:
>@rouilj did you find anything on how to do this ?  I want to do the
>same, can't see any obvious way to do so

Didn't find a way to do this. Waiting on a response from the
developer.

--
				-- rouilj
John Rouillard
===========================================================================
My employers don't acknowledge my existence much less my opinions.

**Comment by riktar** [comment]
If you want customize the card content, you can insert your html in `title` properties of `boards` object.

Here ana example:

```js
"item"  : [                           // item of this board
            {
                "id"    : "item-id-1",
                "title" : "<h1>Hello Boys</h1>"            // title of the item
                "class" : ["myClass",...]
            },
            ...
]
```

**Comment by rbmcgowan** [comment]
thanks for the response @riktar, appreciated.

**Comment by rouilj** [comment]
Ah ok. Is the title injected with innerHTML into the card? I'll give it shot thanks.
