### ISSUE TITLE
removeElement method is not working.

### ISSUE THREAD

**Issue by milpas999** [riktar/jkanban#107]
Trying to remove item from the board, using the item id, shows error.

`kanbanBoard.removeElement(selectedElementId);`

where selectedElementId is the value of the data-eid of the item in board.

calling above method, shows error in console below

`Uncaught TypeError: Cannot read property 'removeChild' of undefined`

**Comment by marcosrocha85** [comment]
Something is missing there. I have [this jsfiddle](https://jsfiddle.net/marcosrocha85/Lk9t483r/) pointing to the **master** branch and everything is fine with removeElement. Do you sure your kanbanBoard variable is set and not null?

**Comment by milpas999** [comment]
Hello Guys, I have figured out the issue,

In one of my project, I was using mongoDB, whoes Ids are in form of alpha numeric character.

But in my current project, I am using Mysql, wholes ids are in integer form, 

The issue occur when i pass an Integer, at an item id to remove id.

I had to change the integer value to string, and the issue resolved.

Btw Thanks for your support...

**Comment by milpas999** [comment]
I am closing this issue, hoping you will do type convert in the library.

Thanks. again
