### ISSUE TITLE
Add Board Button in Boards

### ISSUE THREAD

**Issue by Rampesna** [riktar/jkanban#118]
I want to create 'add new board' button at the all other boards right side

**Comment by marcosrocha85** [comment]
boards.title is a property that accepts HTML, you can add buttons there as you wanted.
See https://jsfiddle.net/marcosrocha85/Lk9t483r/

**Comment by Rampesna** [comment]
My solution is;

/* Other Boards */ ,
{
                    'id': '0',
                    'order': 99999,
                    'title': '<div class="row"><div id="addNewBoard" class="col-xl-12 bg-dark-75-o-25 bg-hover-secondary text-center cursor-pointer" style="border-radius: 2rem"><span class="form-control mt-1 font-weight-bold text-dark-75 editBoardTitle" style="font-size: 12px; border: none; background: transparent"><i class="fa fa-plus fa-sm mr-2"></i>New Boards</span></div></div>',
                    'class': '',
                    'dragBoards': false
                }
                
After Add:

                    kanban.removeBoard('0');
                    kanban.addBoards([
                        {
                            id: '0',
                            order: 99999,
                            title: '<div class="row"><div id="addNewBoard" class="col-xl-12 bg-dark-75-o-25 bg-hover-secondary text-center cursor-pointer" style="border-radius: 2rem"><span class="form-control mt-1 font-weight-bold text-dark-75 editBoardTitle" type="text" style="font-size: 12px; border: none; background: transparent"><i class="fa fa-plus fa-sm mr-2"></i>Yeni Pano</span></div></div>',
                            dragBoards: false
                        }
                    ]);
                    
Is there an easier way?

**Comment by marcosrocha85** [comment]
I guess I don't understanding you. You want to add a new board at the most right of kanban or you want to add a button at every board title?

**Comment by Rampesna** [comment]
https://ibb.co/V9ZpFBj

This is my screen, when I click the 'Yeni Pano' button, I want to create a new board and then the 'Yeni Pano' button will remain on the far right of all boards.

My solution is;

var kanban = new jKanban({
            element: '#tasks',
            widthBoard: '290px',
            dragBoards: true,
            click: function(el) {/* */},
            dropEl: function (el, source) {/* */},
            dragendBoard: function (el) {/* */},
            boards: [
                /* Other Boards */
                {
                    'id': '0',
                    'order': 99999,
                    'title': '<button>Yeni Pano (Add New Board)</button>',
                    'dragBoards': false
                }
            ]
        });
        
When clicked (Add New Board) button i delete the board with the id value of 0 (this is my for my Add New Board Button) and create it again. I'm doing this so that my 'Add New Board Button' can stay on the far right.

**Comment by marcosrocha85** [comment]
Now I could understand you. I guess the best way is the way you're doing because of the current behavior of jKanban. I think would be nice if jKanban had a button to add a board like that, so pull requests are welcome. Oh, and nice board btw. ;)

**Comment by Rampesna** [comment]
Thank you for your nice thought :) As I said, I just wanted to know if there is an easy solution :)
