### ISSUE TITLE
Moving Deleted Board Elements to Another Board

### ISSUE THREAD

**Issue by Rampesna** [riktar/jkanban#119]
How can i move deleted board elements to another baord?

**Comment by marcosrocha85** [comment]
Basically you will have to have id from "Excluded Items" board and do that manually.

* Get element being to "remove";
* Remove it from old board with `removeElement`;
* Use `addElement` to add to new board (Excluded Items).

**Comment by Rampesna** [comment]
> Basically you will have to have id from "Excluded Items" board and do that manually.
> 
> * Get element being to "remove";
> * Remove it from old board with `removeElement`;
> * Use `addElement` to add to new board (Excluded Items).

Thanks Marcos, I'm already using the method as you said right now, but is there an easier way? For ex. may i trigger element drop event for move deleted board elements to another board?

**Comment by marcosrocha85** [comment]
I fear there isn't. By the way, you can develop it and do a PR or hire @riktar for custom behaviors. =)

**Comment by Rampesna** [comment]
I prefer to develop it myself :)
