### ISSUE TITLE
Turn off automatically adding custom properties data to the dom?

### ISSUE THREAD

**Issue by WriterStat** [riktar/jkanban#122]
I'd like to add custom properties, but not have them added to the dom as data.

Is there a way to turn this off?

Thanks!

**Comment by WriterStat** [comment]
Is there an option to set so that custom properties data isn't added to the dom? Thanks!

**Comment by marcosrocha85** [comment]
Unfortunately not at the moment. jKanban uses DOM to store properties. That's part of web concern, I think. It might be great if you could do a MR about it.
