### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by justkidding96** [riktar/jkanban#123]
Hi I've got an error sometimes when initializing the kanban. 

This line triggers the error:
```document.querySelector(e.options.element).dataset.hasOwnProperty("board") ? (url = document.querySelector(e.options.element).dataset.board,```

Could you explain what I'm doing wrong?

**Comment by marcosrocha85** [comment]
When are you initializing jKanban? While page loading of after page completely loaded?

**Comment by justkidding96** [comment]
@marcosrocha85 I have a Vue application. When I get a successful response I initialize the jKanban.

**Comment by justkidding96** [comment]
@marcosrocha85 Any updates about this issue?

**Comment by marcosrocha85** [comment]
Reading your comment again, what are you mean with "I create multiple items with the `createItem` method and then Iinitialize jKanban"? I just can't understand how are you doing. You call new jKanban just only once (after page finishes load), even using Vue. What you have to do is delete/create items according your service return. I used jkanban in a project almost like that and had no issue. What your createItem function does?
