### ISSUE TITLE
Deleting All Boards

### ISSUE THREAD

**Issue by Rampesna** [riktar/jkanban#134]
How can i delete all boards?

**Comment by marcosrocha85** [comment]
jKanban works directly with DOM. In theory, if you remove de DOM elements and assign null to your jkanban instance should work.
We are expecting to develop a [destroy api](https://github.com/riktar/jkanban/issues/84) soon. Pull requests are welcome. 😉

**Comment by Rampesna** [comment]
> jKanban works directly with DOM. In theory, if you remove de DOM elements and assign null to your jkanban instance should work.
> We are expecting to develop a [destroy api](https://github.com/riktar/jkanban/issues/84) soon. Pull requests are welcome. 😉

I will temporarily continue with this method until the API is ready, thanks :)
