### ISSUE TITLE
How can i block drag/drop any board item?

### ISSUE THREAD

**Issue by Rampesna** [riktar/jkanban#139]
I want to block some items dragging, how can i do?

**Comment by Rampesna** [comment]
```
{
  id: id,
  title: title,
  draggable: false // custom data i was add
}
```

I was add custom data(draggable) for item. And i am controlling this data on dragEl function;

```
dragEl: function (el, source) {
    if (el.dataset.draggable === 'false') {
        // How can i stop drag transaction at here?
    }
},
```

I want to stop drag transaction if draggable data is false. I tried `return false;` but it wasn't work.

This is enought for block any item draggable for me.

**Comment by marcosrocha85** [comment]
Use this. https://github.com/riktar/jkanban/issues/112#issuecomment-780541170

**Comment by Rampesna** [comment]
I tried but it gives me an error:

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
// ...
var r = function (e) {
    var t = e.getBoundingClientRect();
    return {
        left: t.left + K("scrollLeft", "pageXOffset"),
        top: t.top + K("scrollTop", "pageYOffset")
    }
}(m);
// ...
```

**Comment by Rampesna** [comment]
I was fixed problem like that;

```
var r = function (e) {
    var t = e.getBoundingClientRect();
    if (t) {
        return {
            left: t.left + K("scrollLeft", "pageXOffset"),
            top: t.top + K("scrollTop", "pageYOffset")
        }
    }
}(m);
```

Thanks!

**Comment by marcosrocha85** [comment]
Very good. Please close the issue.
