### ISSUE TITLE
Howto read DropTo option value for a specific board?

### ISSUE THREAD

**Issue by bairog** [riktar/jkanban#144]
Hello and thank you for your awesome library.
As I can see **dropEl** callback fires even if item cannot be dragged to the target board (**DragTo** option of the source board doesn't have target board Id in it). I need to identify such situations (and don't perform all logic that is called in case of "allowed" drag).
I've started with the following code but I have no idea howto read `DropTo` option value here (I pass an extra `jKanban` value in my function because I need it to find a board):
```
function onDropEl(jKanban, el, target, source, sibling) {
    //FIRST variant to get targetBoardId
    var targetBoardId = target.parentElement.getAttribute('data-id');

    //SECOND variant to get targetBoardId - which of two is the correct one???
    var targetBoardId2 = target.parentElement.dataset.id;

    var targetBoard = jKanban.findBoard(targetBoardId);
   //Howto read DropTo option value here??? 
  
}
```

**Comment by bairog** [comment]
And one more question: am I missing something or there is no special **ItemHover** callback? My idea is to display minimal item info in title and show full item data in a tooltip for example. So hover callback will be ideal for that. Or there is no such and will to use **clicked** callback?

**Comment by bairog** [comment]
@marcosrocha85 maybe you can help me and answer some of that questions?

**Comment by marcosrocha85** [comment]
@bairog you can find a lot of others past "problems" in Closed issues. I suggest you to take a look and try to figure out if some solution fits your needs. For instance, look at this https://github.com/riktar/jkanban/issues/22.

**Comment by bairog** [comment]
> I suggest you to take a look and try to figure out if some solution fits your needs. For instance, look at this #22.

Thank you I've used your [code sample ](https://github.com/riktar/jkanban/issues/22#issuecomment-425184889)
```
var allowedBoards = [];
jkanban.options.boards.map(function (board) {
     if (board.id === $(source.parentElement).data("id")) {
          board.dragTo.map(function (_board) {
               if (allowedBoards.indexOf(_board) === -1) {
                    allowedBoards.push(_board);
               }
          });

          return allowedBoards[0];
     }

     return allowedBoards[0];
});

if (allowedBoards.length > 0 && allowedBoards.indexOf($(target.parentElement).data("id")) === -1) {
       kanban.drake.cancel(true);
       return;
}
```
but slightly modified and simplified it:
```
var allowedBoards = jkanban.options.boards.filter(b => b.id === source.parentElement.dataset.id)[0].dragTo;

if (allowedBoards.indexOf(target.parentElement.dataset.id) === -1) {
        jkanban.drake.cancel(true);
        return;
}
```

**Comment by marcosrocha85** [comment]
> > I suggest you to take a look and try to figure out if some solution fits your needs. For instance, look at this #22.
> 
> Thank you I've used your [code sample ](https://github.com/riktar/jkanban/issues/22#issuecomment-425184889)
> 
> ```
> var allowedBoards = [];
> jkanban.options.boards.map(function (board) {
>      if (board.id === $(source.parentElement).data("id")) {
>           board.dragTo.map(function (_board) {
>                if (allowedBoards.indexOf(_board) === -1) {
>                     allowedBoards.push(_board);
>                }
>           });
> 
>           return allowedBoards[0];
>      }
> 
>      return allowedBoards[0];
> });
> 
> if (allowedBoards.length > 0 && allowedBoards.indexOf($(target.parentElement).data("id")) === -1) {
>        kanban.drake.cancel(true);
>        return;
> }
> ```
> 
> but slightly modified and simplified it:
> 
> ```
> var allowedBoards = jkanban.options.boards.filter(b => b.id === source.parentElement.dataset.id)[0].dragTo;
> 
> if (allowedBoards.indexOf(target.parentElement.dataset.id) === -1) {
>         jkanban.drake.cancel(true);
>         return;
> }
> ```

Nicely done!!! At that time I wasn't able to use filter (I can't remember why). Please close the issue if your problem was solved. I suggest you to create different issues for different questions.

**Comment by bairog** [comment]
> Please close the issue if your problem was solved. I suggest you to create different issues for different questions.

Closed this one as my DropTo issue is solved now. Created separate issues: #148 for **ItemHover** and #149 for **AddForm**
