### ISSUE TITLE
jkanban support swimlane functionality ?

### ISSUE THREAD

**Issue by MilanUnjiya4149** [riktar/jkanban#146]
I want to implement kanban with swimlane.
jkanban support it?

**Comment by marcosrocha85** [comment]
I fear that you can't implement swimlanes with jKanban. This project is, as the name says, Kanban based. So you can implement boards like Trello, Jira Kanban and so on.

**Comment by fwdekker** [comment]
It is not entirely clear to me why jKanban could not implement swimlanes. A large number of Kanban applications provide swimlanes (including Jira Kanban, cited in the comment above), and [the Wikipedia page on Kanban](https://en.wikipedia.org/wiki/Kanban_(development)) also explicitly mentions swimlanes. From what I understand, the Kanban method itself is also not incompatible with using swimlanes. Do I misunderstand this or is there another issue preventing adding swimlanes to jKanban?

**Comment by marcosrocha85** [comment]
I think it's mostly because it's "vanilla" javascript. The only plugin being used is Dragula for drag-and-drop. But we still need pull requests to do that. 🥺

**Comment by fwdekker** [comment]
I see. Then, if I understand you correctly, it's not that swimlanes are inherently incompatible with jKanban, just that it's _currently_ not feasible yet?

**Comment by riktar** [comment]
@FWDekker jKanban is a little JS library that implements ONLY Kanban board (drag and drop and some integrations with cards) in vanilla ways using a JSON to build all the board. 

It's not a project manager software.

You can integrate a swimlane graph in jKanban, but it's not a prerogative of this library, so you must have to implement the adapter from swimlane graph to jKanban's JSON.

**Comment by fwdekker** [comment]
Thank you for the clarification, that makes sense to me :-)
