### ISSUE TITLE
Is there an ItemHover callback?

### ISSUE THREAD

**Issue by bairog** [riktar/jkanban#148]
Am I missing something or there is no special **ItemHover** callback? My idea is to display minimal item info in title and show full item data in a tooltip (**Bootstrap** or **jqueryui** for example). So hover callback will be ideal for that. Or there is no such and will to use **context** callback?

**Comment by marcosrocha85** [comment]
No, there's not. But you can handle that with a simple css class. Eg:
```
...
"item"  : [
{
  "id"    : "item-id-1",
  "title" : "Item 1"
  "class" : ["myItemHoverClass",...]
},
{
  "id"    : "item-id-2",
  "title" : "Item 2",
  "class" : ["myItemHoverClass",...]
}]
...
```
And implement something (jQuery probably) like:
```
$(".myItemHoverClass").on("hover", function(e) {
  if(e.type === "mouseenter") {
    console.log("over");
  }
  else if (e.type === "mouseleave") {
    console.log("out");
  }
});
```
