### ISSUE TITLE
dragBoards and dragItems have no effect

### ISSUE THREAD

**Issue by richardklingler** [riktar/jkanban#155]
Regardless if setting dragBoards or dragItems to true or false, boards and items can still be dragged around and placed.

Only dragTo setting per board has an effect.

With this settings everything is dragable:

`    var kanban1 = new jKanban({
        element:'#myKanban',
        dragBoards: false,
        dragItems: false,
        boards  :[....],
`

**Comment by richardklingler** [comment]
Seems this is also only available in jkanban.js and not in jkanban.min.js

**Comment by marcosrocha85** [comment]
Thank you for your feedback.
