### ISSUE TITLE
How to dynamically set data-eid with addELement()?

### ISSUE THREAD

**Issue by richardklingler** [riktar/jkanban#156]
Trying now to implement a shop category edit/sorting function with jkanban where each board represents a certain hierarchy level...

When I set the top levels in a board like this:

`                'item'  : [
                    {
                    	'id': 1,
                        'title':'<input type="text" value="Living">',
                    },
`
I can get the the clicked item with "el.dataset.eid" and load via Ajax the next level into the second board, where I then also set the id dynamically:

`	      		kanban1.addElement('_working', {
	      			title: '<input type="text" value="' + data[i].name + '">',
	      			id: data[i].id,
	      		});
`
But when looking at the inspector in firefox I don't see any data-eid="x" set...so clicking on the second level items have no effect...

How can I set this data-eid so it can be used in the click handler?

thanks in advance
richard

**Comment by richardklingler** [comment]
Looks this feature is only available in jkanban.js and not in jkanban.min.js...

Also getParentBoardID() is missing in jkanban.min.js....

Would be nice if function differences would be documented :-)

**Comment by marcosrocha85** [comment]
@riktar next time you tag a new release, can you build css either?
