### ISSUE TITLE
Struggeling between 2 versions

### ISSUE THREAD

**Issue by rmaxx** [riktar/jkanban#160]
I use this kanban board for sortable (short) forms. However im stuck since i need to drag something inside the kanbanitem.
When i use the latest version of th escript, this works, but checkboxes no longer work.
When i use an older version my checkboxes work, but i cant use the handler (i use a headerbar to drag)

Is this a known issue (either one) 

to demostrate:  Add a checkbox to one of the boxes with inspector tool:
https://www.riccardotartaglia.it/jkanban/  > works , but no handlers ?
https://www.cssscript.com/demo/draggable-kanban-board/  > doesnt work
Latest version from git > handlers work, checkbox doesnt work

**Comment by WriterStat** [comment]
See #172 - Near bottom of issue text the 1-line fix is mentioned. Browser event propagation has to be turned back on in jkanban.js - I realize this may be from a while back, but in case someone else needs the answer.
