### ISSUE TITLE
Cancel drag

### ISSUE THREAD

**Issue by marcosrocha85** [riktar/jkanban#17]
I'm trying to cancel a drag event in order to prevent moving cards on a automatic board, but when I call `jkanban.drake.cancel(true)` the dragula raises an exception saying "el is null" on touchy function.
Do you have any suggestion to implement a "beforeDrag" event in order to validate if a card can be moved? I'm intended to develop that on jKanban.

**Comment by marcosrocha85** [comment]
For those who want do that outside jKanban, you can do `jkanban.drake.cancel(true)` at dropEl event. For example:
```
jkanban = new jKanban({
...
dropEl: function(el, target, source, sibling) {
    if (myValidationOfCanDrag) {
        jkanban.drake.cancel(true);
    }
}
...
);

**Comment by marcosrocha85** [comment]
Noticed that `dropEl` fires even when the property `"dragTo"` is set and the card is dropped on a _target_ board that supposely shouldn't accept dragging from _source_ board. Is it possible to get the `"dragTo"` of target at `dropEl` element?

**Comment by marcosrocha85** [comment]
> Noticed that `dropEl` fires even when the property `"dragTo"` is set and the card is dropped on a _target_ board that supposely shouldn't accept dragging from _source_ board.

Suggestion: Don't fire dropEl when the item is now allowed to receive elements from dragTo property.

**Comment by riktar** [comment]
fixed in: https://github.com/riktar/jkanban/commit/d7ef0efec048595cd0dba34744028b19e55af19c

**Comment by adryx92** [comment]
I'm having the same issue. If I drop an item on a non-allowed target, the dropEl is still fired.
