### ISSUE TITLE
Is there any way to collapse kanban board?

### ISSUE THREAD

**Issue by Shum1905** [riktar/jkanban#171]
Now I'm setting a button as a header above kanban board. 
I tried to set another id to identify the part to collapse other than the id for kanban element so I can collapse it when i click that button but it didn't work.

Is there any way to collapse kanban board?

Attached is the code that I'm using. (sorry i couldn't use markdown well...)
[code-sample.txt](https://github.com/riktar/jkanban/files/9204852/code-sample.txt)

**Comment by marcosrocha85** [comment]
I think [this fiddle](https://jsfiddle.net/marcosrocha85/sL24hvxn/) can bring you some clue.

**Comment by Shum1905** [comment]
Seems great!!
Thank you very much!!
