### ISSUE TITLE
Which js minification software does jkanban use

### ISSUE THREAD

**Issue by WriterStat** [riktar/jkanban#179]
Hi, Thanks for some great kit.

I've made some modifications that are app specific. 

Which js minification software does the jkanban project use? Thanks!

**Comment by marcosrocha85** [comment]
Hello there. You can run `npm run build` to build/minify your sources.

**Comment by WriterStat** [comment]
Thanks! I used another minification software. I like to stay away from node js, npm complexity etc...when not needed, it makes an app feel like it's got serious bloat. I only use it when I'm writing in Angular or Vue frameworks.

To be honest I feel much happier writing web app software without all the full-on frameworks. Alot of us are starting to move away from node js on the frontend. Standard/vanilla js for the frontend works just as well and has grown up/filled in a lot over the last few years.
