### ISSUE TITLE
importing jkanban/dist/jkanban.min.js file throws an error

### ISSUE THREAD

**Issue by Javier1995** [riktar/jkanban#187]
I am using vuejs3 and vite 4

My code is:
```
<script>
import("jkanban/dist/jkanban.min.js");
import("jkanban/dist/jkanban.min.css");

export default {
  name: "Kanban",
  mounted() {
    const bootstrap = this.$store.state.bootstrap;

    (function () {
      if (document.getElementById("myKanban")) {
        var KanbanTest = new jKanban({
          element: "#myKanban",
          gutter: "10px",
.........
```

![image](https://user-images.githubusercontent.com/11432889/232345266-037e8eca-a222-4ad7-b72f-55724a14c718.png)

**Comment by marcosrocha85** [comment]
Unfortunately, jKanban doesn't support ESM modules. Have you tried `import * as jKanban from "jkanban/dist/jkanban.min.js"`?

**Comment by Javier1995** [comment]
Thanks! I will give it a shot. It was working fine using vue cli but migrated it to vite

**Comment by marcosrocha85** [comment]
@riktar can you close this issue?

**Comment by tdeuling** [comment]
I've exacly the same issue by using the current master. 
I try to import with `import * as jKanban from "jkanban";` but it throws the error:

```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'jKanban')
    at jkanban.js?bust=1704019215:14:16
    at 1.dragula (jkanban.js?bust=1704019215:609:3)
    at o (jkanban.js?bust=1704019215:1:265)
    at r (jkanban.js?bust=1704019215:1:431)
    at jkanban.js?bust=1704019215:1:460
```

![image](https://github.com/riktar/jkanban/assets/1298841/890d7b76-15dc-4707-ab15-6da8c946a172)

@Javier1995 how did you solve this issue!?
