### ISSUE TITLE
JKanban drag and move not working properly when we use the mobile view

### ISSUE THREAD

**Issue by oricosta88** [riktar/jkanban#193]
Hi recently we implemented into our website a mobile view for mobile, tablet users and one of our pages use JKanban. When we change the view into mobile the jkanban shows fine and the events of click and selectable works too, but when we try to drag or move the Kanban element it just buggs and instead of moving the Kanban it scrolls to the sides or up depending of the movement. It is a way to change the kanban into mobile mode or i would need to change some functions to make this work? I was wondering if could change the drag function and stop the scroll in that moment.

I attach a video of the JKanban bugged 
[https://youtube.com/shorts/_SMIM9Owsjg](url)

**Comment by WriterStat** [comment]
Hi, hope this finds you doing well. I think I can help you.

Quick question: Is this a personal site? Open source? A company site? Or a client site?

I have developed a fix, that we use in our software which works well for mobile, tablet users, and touchscreens, but need to know the above, thanks.

I hope I'm not overstepping my bounds in saying that the current library doesn't internally come with this.

Best, -Wrtr

**Comment by marcosrocha85** [comment]
> Hi, hope this finds you doing well. I think I can help you.
> 
> Quick question: Is this a personal site? Open source? A company site? Or a client site?
> 
> I have developed a fix, that we use in our software which works well for mobile, tablet users, and touchscreens, but need to know the above, thanks.
> 
> I hope I'm not overstepping my bounds in saying that the current library doesn't internally come with this.
> 
> Best, -Wrtr

Actually you're right. jKanban was developed to be a vanilla javascript package, it actually uses Dragula to do the drag-n-drop feature but that's all. I'm not the owner of the project, but I think we should upgrade it to a more embracing solution. I made a Trello like kanban with this plugin, but I had to do most of it by hand in the code. @WriterStat if you could share your fix in here, that would be great. Thanks in advance.

**Comment by rouilj** [comment]
Maybe applying:
```
touch-action: pan-y;
```
to the body of the kanban will do the trick?

I limited it to the x direction since I assumed the kanban columns wrapped on top of each other, so you would scroll down to drop in a different column.

Also there is an issue on stopping page scrolling while dragging for dragula at: https://github.com/bevacqua/dragula/issues/487.

**Comment by oricosta88** [comment]
> Hi, hope this finds you doing well. I think I can help you.
> 
> Quick question: Is this a personal site? Open source? A company site? Or a client site?
> 
> I have developed a fix, that we use in our software which works well for mobile, tablet users, and touchscreens, but need to know the above, thanks.
> 
> I hope I'm not overstepping my bounds in saying that the current library doesn't internally come with this.
> 
> Best, -Wrtr

Its a company site if you could share this fix would be so nice for me!

**Comment by oricosta88** [comment]
> Maybe applying:
> 
> ```
> touch-action: pan-y;
> ```
> 
> to the body of the kanban will do the trick?
> 
> I limited it to the x direction since I assumed the kanban columns wrapped on top of each other, so you would scroll down to drop in a different column.
> 
> Also there is an issue on stopping page scrolling while dragging for dragula at: [bevacqua/dragula#487](https://github.com/bevacqua/dragula/issues/487).

I already tried it does not work for me the touch-action

**Comment by WriterStat** [comment]
> Maybe applying:
> 
> ```
> touch-action: pan-y;
> ```
> 
> to the body of the kanban will do the trick?
> 
> I limited it to the x direction since I assumed the kanban columns wrapped on top of each other, so you would scroll down to drop in a different column.
> 
> Also there is an issue on stopping page scrolling while dragging for dragula at: [bevacqua/dragula#487](https://github.com/bevacqua/dragula/issues/487).

Note: I don't think the above suggested will work, although I could be wrong. Basically, what causes this detachment in the drag of an item happens in the entire container and possibly even outside the container in the entire page as well, basically you have to look at the problem as both the touch events drag and the regular js browser events drag each telling the specific dragged item to do different things in the page/container. Which causes the detachment and jump of the item. So...touch-action: pan-y; probably doesn't fix that for the item. Hope helps.

**Comment by WriterStat** [comment]
Hi @oricosta88 - Quick questions, does the company sell the software or is it in-house use for something?Thanks for the info. Where will it be used? Thanks again.

**Comment by oricosta88** [comment]
> Hi @oricosta88 - Quick questions, does the company sell the software or is it in-house use for something?Thanks for the info. Where will it be used? Thanks again.

The company itself its a software of internal business management and the clients use the software to manage his company, this it will be used only for one specific client that wants the functionality to use one of the pages in tablet, the page its a Kanban of task of the business

**Comment by WriterStat** [comment]
Hi @oricosta88 - I have added you to a Github Discussion repository. If you accept your invitation, you can quick select the corresponding issue area and we can quick discuss and depending on info get you moving ahead. Note this update probably also fixes the Dragula.js problem.

**Comment by oricosta88** [comment]
Hi @WriterStat I was in vacation since last wednesday sorry for the discconection. I was gona ask you how i should make the payment with any kind of message to know it was me and if i had to do it as a donation in the page you linked.The discussion you added me in was closed or disappered is there any problem with it? Another question when we make the payment how we gona proced you gona come in a discord server and try to fix it or how you will help us?

**Comment by WriterStat** [comment]
Hi @oricosta88 while this is probably/definitely not the right place for this. I responded to your request on Friday, Sept 6th and on Monday the 9th. Which you got/read. Didn't hear back Mon, Tues, Wed, after that, no questions, no response, no payment, no note of vacation, and not until today, Sept 17th. Feels a bit unprofessional. With that, and no response made, after a week I removed the repository access. I just don't have time to waste. First off, you could have asked these questions, Mon, Tue, or Wed, or verified all things with direct messages in the repository. At this point my calendar, no longer has those previous openings available, those dates have past. With your software not going to be released back into open source.

**Comment by riktar** [comment]
I think this has gone too far.

Please use mail and not GitHub issues for your business.
