### ISSUE TITLE
How can I know which board was the elemnt dropped to?

### ISSUE THREAD

**Issue by kojaktaha** [riktar/jkanban#23]
How can I Know which board was the element dropped to?

**Comment by marcosrocha85** [comment]
Hello @kojaktaha, there is an event called `dropEl` which you can track where element was dropped.
```javascript
jkanban = new jKanban({
    element: '#your_element',
    dropEl: function(el, target, source, sibling) {
        console.log(target);
    }
}
```

**Comment by kojaktaha** [comment]
> 
> 
> Hello @kojaktaha, there is an event called `dropEl` which you can track where element was dropped.
> 
> ```js
> jkanban = new jKanban({
>     element: '#your_element',
>     dropEl: function(el, target, source, sibling) {
>         console.log(target);
>     }
> }
> ```

Thanks

**Comment by bazzacad** [comment]
I have this question too. The "target" shows me all the elements on the board I dropped on, but how do I get the ID of the board I dropped on?
![image](https://user-images.githubusercontent.com/23222121/46323018-0808c880-c5a1-11e8-9013-a550c46b5882.png)

I want these IDs:
![image](https://user-images.githubusercontent.com/23222121/46323043-2a024b00-c5a1-11e8-8aff-f0b672144d37.png)

**Comment by kojaktaha** [comment]
use : target.parentNode.dataset.id

**Comment by marcosrocha85** [comment]
Or if you're using jQuery: `$(target.parentElement).data("id")`

**Comment by bazzacad** [comment]
Thanks very much both of you.
