### ISSUE TITLE
Feature Request: Footer option

### ISSUE THREAD

**Issue by bazzacad** [riktar/jkanban#26]
Like the header, have the ability for a footer with it's own class. So you could total up some of the custom data options.

**Comment by marcosrocha85** [comment]
jKanban already adds a footer DOM to a board. In my case, I add contents to that in order to create new items instead of use jKanban native add button. @bazzacad, what kind of data you want do display at footer?

**Comment by bazzacad** [comment]
Thanks for the info. How to I access the footer? You're not referring to the AddForm method are you?
I have custom data on my elements for staff work hours. I'd like to total them up in the footer.

**Comment by marcosrocha85** [comment]
No, if you look at developer tools you will see a <main> tag and after that a <footer>. I access that by doing:
```
var board = jkanban.findBoard("myBoardId");
$(board).find("footer").html("<strong>Footer is Here!</strong>");
```

**Comment by riktar** [comment]
@bazzacad jKanban does not allow you to configure the content of a board's footer, but it automatically creates the <footer> tag in a board that you can easily access using javascript.

If you use jQuery you can use the @marcosrocha85 solution.
