### ISSUE TITLE
Restricting which boards to drag items to

### ISSUE THREAD

**Issue by ramanbuttar** [riktar/jkanban#3]
First of all, this is an elegant, clean, and minimalist solution and I'm going to start using it in my internal project.

I have one feature request. I'd like to specify for each board the titles/ids of other boards the items can be dragged to.

Maybe even have a default option to only be able to drag items to adjacent boards.

**Comment by riktar** [comment]
@ramanbuttar Thank you for your compliments.
I've added "dragTo" option for board object, clone and give a look to the "example" folder.

Cheers
