### ISSUE TITLE
get the ID of source board on dropEl method

### ISSUE THREAD

**Issue by SachinAnnam** [riktar/jkanban#34]
Hello Sir,
I am using this jkanban in SharePoint and am trying to change the status of dragged item using dropEI method.
To achieve this, i thinking to invoke a custom method using element ID and board ID.
Am able to get the element ID but i am stuck with board ID.

Please help me with some snippet so that i can proceed with this.

**Comment by marcosrocha85** [comment]
Hello @SachinAnnam, you are using dropEl event aren't you?
You can get parent board from item by doing some DOM calls:
```javascript
dropEl: function(el, source, target, siblings) {
  console.log(el.parentElement.parentElement.id); // will output your boardId
}
```

**Comment by viniciuszim** [comment]
How can I get the board id and board order when I drag the whole board?
