### ISSUE TITLE
Drag and Drop in mobile

### ISSUE THREAD

**Issue by F-Medeiros** [riktar/jkanban#35]
Is plugin not compatible with mobile?

**Comment by rhuodox** [comment]
Hi!

I tested in my smartphone (Android 8.1) and works fine, with without any adaptation.

Regards.

**Comment by marcosrocha85** [comment]
I use it on an Android and iPad and can use it very well. I can drag and drop items, rearrange them and even touch on it to open my jQuery modal forms.
