### ISSUE TITLE
Copy item between boards

### ISSUE THREAD

**Issue by rhuodox** [riktar/jkanban#36]
Hey there,

How make a copy of item between boards? I need use some extension or adaptation from Dragula or exists some function or option for the item?

Regards.

**Comment by iceaceice** [comment]
Hi, I'm using jKanban for my project I'm trying to figure it out on how to insert new board using the addElement with position.

I did like:
jkanban.addElement(newBoard, {
    'id': currentItem.dataset.id,
    'title': currentItem.innerHTML
},
1
);

Like that but it always add at the bottom of list of  boards.

I don't what I'm doing wrong or if I'm doing right to insert new board to specific position I want. Need some help for this. Thanks in advance whoever help.
