### ISSUE TITLE
Move board programmatically

### ISSUE THREAD

**Issue by viniciuszim** [riktar/jkanban#38]
How can I move a board programmatically?

I want to fix a board in the first position. So I want to move back to the initial position even if another board has been moved to the first one.

I know that I can make a board not draggable, but if you change another card for that position, it will be moved.

**Comment by viniciuszim** [comment]
I have tried this code, but it didn't work:

> dropBoard: function(el, target, source, sibling) {
>console.log("dropBoard id: " + el.dataset.id);
>             if (el.dataset.id === "_todo") {
>                 kanban3.drake.cancel(true);
>             }
>         }

the drake.cancel method doesn't work

**Comment by marcosrocha85** [comment]
Hello @viniciuszim, to cancel board drop event, please use kanban.drakeBoard.cancel(true);

https://jsfiddle.net/zkjfemgL/
