### ISSUE TITLE
Add class in items

### ISSUE THREAD

**Issue by cmparrela** [riktar/jkanban#43]
It would be nice if were possible to add class to items like already have in boards

**Comment by cmparrela** [comment]
I made a modification to use in my projeto, i added in line 258 next comment  `//create item`

```php
if (itemKanban.class != '' && itemKanban != undefined) {
    nodeItem.classList.add(itemKanban.class);
}
```

**Comment by marcosrocha85** [comment]
Hello @cmparrela, in a project of mine I set cover image by jQuery. I think css for an item would be handy. I can do a pull request for that. Thank you for your suggestion.

**Comment by adryx92** [comment]
I also made a modification to add items with specific classes in ```addElement``` function:

```javascript
this.addElement = function(boardID, element, className) {
    //...
    if (className)
        nodeItem.classList.add(className);
    //...
}
```

**Comment by Mikeproove** [comment]
Hi Guys

Is there any update on this ?

And if it's already implemented, how do I set the class of an item from the start ?

Cheers
Mike

**Comment by riktar** [comment]
@Mikeproove @cmparrela 
Now is possible to add custom classes to an item.
```
{
                "id"    : "item-id-1",        // id of the item
                "title" : "Item 1"            // title of the item
                "class" : ["myClass",...]     // array of additional classes
}
```
https://github.com/riktar/jkanban/commit/e3fa10ad69133e4b29fa6c5183c185631b90617c
