### ISSUE TITLE
it can use npm?  I want use it to react so need npm

### ISSUE THREAD

**Issue by powerProgrammerMa** [riktar/jkanban#44]

**Comment by marcosrocha85** [comment]
Actually I guess isn't that hard to do. I can take a look this weekend.

**Comment by powerProgrammerMa** [comment]
thanks

**Comment by riktar** [comment]
here: https://www.npmjs.com/package/jkanban

**Comment by dtamm** [comment]
How about an documentation on how to use it with NPM (and maybe as require or ES6 module)? Just tested the npm package, i am getting an error when using it (may be project specific, but the error looks like this: jkanban__WEBPACK_IMPORTED_MODULE_2___default.a is not a constructor), shall i raise a new issue for this?
