### ISSUE TITLE
Option to disable drag/drop on the board

### ISSUE THREAD

**Issue by ramanbuttar** [riktar/jkanban#5]
Another feature request: Provide an option to keep the boards affixed and not allow drag/drop operations on the board itself.

**Comment by riktar** [comment]
Now you can use the `dragBoards` option to activate drag/drop on all boards

**Comment by brunonetadmin** [comment]
I don´t see any option to not allow drag inside the original board. The dropEl its called even if i drag a item to the same board. Its possible to create this 'feature'?

**Comment by marcosrocha85** [comment]
Hi @brunonetadmin , in fact dropEl is called even at the same origin. Are you trying to prevent reordening? Tell us more about what are you trying to achieve.

**Comment by brunonetadmin** [comment]
I´m trying to execute the action of consulting(ajax) the backend, and showing the status change notifications, but i don´t wanna make anything if the item its dropped in the same column. And i´m not using reordering itens.

And how i trigger a custom action for example, if i try to move a item that are forbidden to go to that column?

**Comment by marcosrocha85** [comment]
You can check if source and target are the same. If so, you don't fire ajax request. ;)
```javascript
dropEl: function(el, source, target, siblings) {
    if (source === target) {
        return;
    }

    $.ajax( //...
}
```
