### ISSUE TITLE
Not reactive when Bind boards array as vuejs data property

### ISSUE THREAD

**Issue by akramwahid** [riktar/jkanban#51]
I am trying to bind the boards array as a data property in vuejs, on initial page load, it take all the array item and render boards correctly, however when i do modification to vue array it doesnot affect in UI, looks like kanban board are not reactive, 

Do you have any function to refresh or rebuilt the boards from scratch, so when I do any changes to vue data property, I can rebuilt the boards. I tried to run the `init` function, however it just duplicated all the baords with changes as well, if you have a function to remove all board elements and boards with single function call, then it will be easy to delete and re call the init function to make it like reactive

**Comment by marcosrocha85** [comment]
Unfortunately, I fear jKanban is not fully compatible with Vuejs. I use jKanban in a Vue application but my events are handled manually.

**Comment by akramwahid** [comment]
> 
> 
> Unfortunately, I fear jKanban is not fully compatible with Vuejs. I use jKanban in a Vue application but my events are handled manually.

can you please give me some tips on how you are handling it manually, 
I am planning to go in this way, when I do changes to vue data property, I will loop through the boards array and remove them from UI and run the jKanban `init` function to build it again?, what you think, is this approach correct?

**Comment by marcosrocha85** [comment]
I don't think call ```init```every time is a good practice. You can use ```watch``` to update your jKanban. In that case, you should add and remove items according your Vue model. Look this fiddle to have an idea. https://jsfiddle.net/marcosrocha85/Lk9t483r/

**Comment by akramwahid** [comment]
yes, I tried with `init` and it was not successful, it raises unexpected errors and disable the kanban board fully, so I am going with manually option as your suggestion..
