### ISSUE TITLE
Get the order of elements on a board

### ISSUE THREAD

**Issue by akramwahid** [riktar/jkanban#52]
I want to save the order state of elements on the board in the backend db. I know we can listen for call back `dragendEl` or `dragEl` in order to detect the item reordering inside a board, how can I get the new order when an item is reordered, 
I also want to store the order of the Board as well when I enable `dragBoards` , your help is kindly appreciated

**Comment by marcosrocha85** [comment]
Hello @akramwahid , you will have to get the elements and iterate over it. Like:
```
dropEl: function(el, target, source, sibling) {
  	var _target = $(target.parentElement);
    var sorted = [];
    var nodes = jkanban.getBoardElements(_target.data("id"));
    var currentOrder = 0;
    nodes.forEach(function(value, index, array) {
      sorted.push({
        "id": $(value).data("eid"),
        "order": currentOrder++
      })
    });
    $("#working_sort_order").val(JSON.stringify(sorted));
  },
```

https://jsfiddle.net/marcosrocha85/Lk9t483r/

**Comment by akramwahid** [comment]
thanks for this, can you please tell me how to do similarly to get the new order of boards when boards are moved arround

**Comment by akramwahid** [comment]
thanks for this, this solved my problem
