### ISSUE TITLE
Some div in board title

### ISSUE THREAD

**Issue by zertex** [riktar/jkanban#56]
If I put some div in board title, ex.: 
```'
<div class="row">
<div class="col-md-9">Board Title</div>
<div class="col-md-3" style="text-align: right">Menu</div>
</div>'
```
Drag system failed... How I can fix it?

**Comment by marcosrocha85** [comment]
Hello, @zertex .
I don't know why you want to use div to achieve a menu, but you can make that work by adding the class kanban-title-board to both of divs (row, col-md-9 and col-md-3 as well).

Perhaps you can use native jKanban button by using the [buttonContent](https://github.com/riktar/jkanban#usage) attribute.

**Comment by zertex** [comment]
I add dropdown class and menu. Thanks
