### ISSUE TITLE
Change element board

### ISSUE THREAD

**Issue by zertex** [riktar/jkanban#57]
How I can move item to another board by API?

I use
`dropEl : function (el, target, source, sibling) {}`
then
`kanban.addElement(board_id, el);`

But element without content
![2222](https://user-images.githubusercontent.com/6353201/62892855-e72d0a00-bd51-11e9-89b2-b7fd19443341.JPG)

P.S. I found moveElement method, but it also has that issue...

**Comment by marcosrocha85** [comment]
Hello again @zertex , have you read issue #36?

**Comment by zertex** [comment]
Thank you! Sorry, I skip #36

**Comment by kevzlou7979** [comment]
@zertex Just curious, How did you create your custom Kanban Items (especially the first item) with custom DOM elements inside the item?

**Comment by zertex** [comment]
> 
> 
> @zertex Just curious, How did you create your custom Kanban Items (especially the first item) with custom DOM elements inside the item?

The title element includes all html code

**Comment by kevzlou7979** [comment]
Oh i see thanks for the information.
