### ISSUE TITLE
Customize Kanban Item

### ISSUE THREAD

**Issue by kevzlou7979** [riktar/jkanban#60]
Hi there,

Is there a way we can create our own kanban custom DOM elements like this?
![image](https://user-images.githubusercontent.com/3138071/64574036-53764a00-d3a0-11e9-8b49-78082b8f2e69.png)

The image above indicates we had four dom elements that needs to be placed on Kanban Item.

Thanks,
Mark

**Comment by marcosrocha85** [comment]
@kevzlou7979 , does the [comment of @zertex](https://github.com/riktar/jkanban/issues/57#issuecomment-529800481) from #57 solved your issue?

**Comment by kevzlou7979** [comment]
Yeah we can close this issue, thanks for the library
