### ISSUE TITLE
add changed function

### ISSUE THREAD

**Issue by thijsd** [riktar/jkanban#62]
It would be nice to have a function that is called when something changed.
When an element is added, replaced, or a board was added,...

```
var kanban = new jKanban({
    changed           : function (el) {
        // something changed
        // e.g. add code to save items to server
    }, 
```

**Comment by riktar** [comment]
Hi @thijsd, you can use the callbacks of jKanban.
You can find them in the [README](https://github.com/riktar/jkanban#var-kanban--new-jkanbanoptions)
