### ISSUE TITLE
Get board id when an item is been moved to it 

### ISSUE THREAD

**Issue by hayjay** [riktar/jkanban#67]
Currently, when an item is been moved to a board, three things are been returned namely :
1. el
2. target
3. source
4. siblings

All these are good to have, but i guess it would be nice if we can have the board id the item is been moved to as well. #dropEl function handles this

**Comment by riktar** [comment]
Hi @hayjay you can access to the boards `data-id` simply using Javascript:
`
dropEl: function(el, target, source, sibling){
  console.log(target.parentElement.getAttribute('data-id'));
  console.log(source.parentElement.getAttribute('data-id'));
}
`
