### ISSUE TITLE
Drag does not work in mobile mode

### ISSUE THREAD

**Issue by KeenthemesHub** [riktar/jkanban#73]
Hi,

Thanks for the great plugin.  

We encountered a little issue.  Could you please check our test video here;
https://www.loom.com/share/05daa5de83c940bf9c7da306fa08e65f

We used your official example file; `jkanban-1.2.0/example/index.html` for this test.
It will work only when page initializes in desktop mode, but not in mobile mode. 

Thanks

**Comment by riktar** [comment]
Hi, can you give me more information about what type of browser are you using?

I've tried on Chrome, and it's works:
https://streamable.com/t7sxa

**Comment by KeenthemesHub** [comment]
Hi, thank you for your reply. I tried on Chrome. Can you try to make it on a smaller screen? Less than 600px maybe. Need to refresh the page. every time size change.

Thanks

**Comment by riktar** [comment]
@KeenthemesHub It works...
https://streamable.com/hynp8

**Comment by KeenthemesHub** [comment]
Sorry, I should be more clear. Could you please try these steps.
1) Open in mobile mode (smaller screen)
2) Refresh page (F5)
3) Retry to drag

Thank you for your patience

**Comment by riktar** [comment]
In the example, there is `responsive: "700",` prop setted, this prop enable drag only if the window size if major of the value setted.

```json
var defaults = {
//...
     widthBoard: "250px",
      responsive: "700",
...//
```

**Comment by KeenthemesHub** [comment]
Thank for your help 😊
