### ISSUE TITLE
How to disable dragging feature for particular Board column in list of column

### ISSUE THREAD

**Issue by bharathyathiraj** [riktar/jkanban#81]
Hi All,

I have added 3 boards for my kanban board, i want to disable drag feature for last board items, kindly let me know how to achieve this .

Please find attached picture for more detail of my question.
![kanbanBoard](https://user-images.githubusercontent.com/61837084/75992365-db877780-5f1d-11ea-80f1-c022fdfb72d9.jpg)

**Comment by riktar** [comment]
Hi @bharathyathiraj 
try this when you define your object boead:

```json
{
        "id"    : "board-id",
        "title" : "Working"
        "dragTo": ['board-id'],
        /*... other props */
}
```

This will allow to drag&drop the item only in same board

**Comment by bharathyathiraj** [comment]
Yes this solution works....Thanks a lot  @riktar

**Comment by bharathyathiraj** [comment]
> Hi @bharathyathiraj.
> Try this when you define your object board:
> 
> ```js
> {
>         "id"    : "board-id",
>         "title" : "Working"
>         "dragTo": ["board-id"],
>         /*... other props */
> }
> ```
> 
> This will allow to drag&drop the item only in same board

This solution works...Thanks a lot @riktar

**Comment by riktar** [comment]
ok, close :+1:
