### ISSUE TITLE
Delete board item

### ISSUE THREAD

**Issue by aayu-ramola** [riktar/jkanban#83]
I want to delete items on the board. I added a delete icon for each element but do not how to call removeElement API. 
I am performing some other action on

click  : function (el) {},

**Comment by marcosrocha85** [comment]
You should call board's `removeElement` function. In order to do that, you should pass id as parameter. In your code, you will have to have the element's id and call a function to remove it, [as you can see here](https://jsfiddle.net/marcosrocha85/Lk9t483r/).

**Comment by aayu-ramola** [comment]
@marcosrocha85 I think you did not get my issue.
I have updated the fiddle. 
https://jsfiddle.net/q3choj2s/1/

When I click remove button first kanban callback 'click' is calling and after that, the custom function defined on click.

On button click, I want to avoid calling kanban callback 'click'.

**Comment by marcosrocha85** [comment]
Ok, I understood now. In fact my kanban does not use fireable elements in items. By the way, I guess you need [this](https://stackoverflow.com/a/387750/5078248).
