### ISSUE TITLE
Feature Request: Add Elements to Item

### ISSUE THREAD

**Issue by rayoray** [riktar/jkanban#86]
Is it possible to add additional elements to the item (example: Labels) and have it displayed on the card?

```
"item"  : [                                       // item of this board
            {
                "id"    : "item-id-1",                // id of the item
                "title" : "Do Something!"            // title of the item
                "label" : [                         // labels of the item
               {
                 "name": "label 1",
                  "color": "00ac0f",
               }
                ],
            },
        ]
```

![image](https://user-images.githubusercontent.com/63407006/81145147-0b540980-8fb9-11ea-9901-20e6e94b0367.png)

**Comment by lb-** [comment]
@rayoray - the docs do not state it explicitly, but anything you put in the `title` attribute will be added as children of the item element. This includes html.

For example, the following will render the html in the board's item.

```
"item"  : [
  {
    "id": "item-id-1",
    "title" : "<div>Do Something!</div><div class="labels><span style="background-color: 00ac0f;">Label 1</span></div>"
  },
]
```

**Comment by riktar** [comment]
@lb- was right! Close
