### ISSUE TITLE
Multi classes for board titles 

### ISSUE THREAD

**Issue by dr-jonathan-jeffery** [riktar/jkanban#89]
In the documentation it says that a board header can have multiple classes added:

 ```
   {
        "id"    : "board-id-1",               // id of the board
        "title" : "Board Title",              // title of the board
        "class" : "class1,class2,...",        // css classes to add at the title
```

However, it you do include multiple classes in a comma-separated string, the are rendered a single long class with commas in the name, rather than a space-separated series of individual classes:

`<header class="kanban-board-header Class1,Class2,Class3"><div class="kanban-title-board">Backlog</div>`

**Comment by marcosrocha85** [comment]
I tested this one and couldn't reproduce the issue. Can you provide an example?

**Comment by riktar** [comment]
I couldn't reproduce the issue, closed.
