### ISSUE TITLE
Implementing package.json/server

### ISSUE THREAD

**Issue by 11fishem** [riktar/jkanban#9]
Hi!

I'm a bit of a noob with using servers and package.json, I have a project i'm implementing this into and am having some trouble with the package.json and getting the server running to save changes made while using the kanban board. I've included a link to the project, would be able to talk over google hangouts as well!

https://glitch.com/edit/#!/studio821?path=package.json:16:46

**Comment by riktar** [comment]
Hi @11fishem jKanban it's a Javascript library and can be inserted into your pages by simply including files in the `dist` folder.

If you want to save the data of your board you can implement any server side solution (PHP, Node, etc...) and use the `events` provided to save data on your database.

ex. `dragendEl` fires when you drop a board's element, so you can make an AJAX request to a your script that save the data

Please read the`README.md` file and take a look in the `example` folder.

Live example of working code:
https://codepen.io/riktar/details/KqZpgL
