### ISSUE TITLE
Npm audit shows this high vulnerabilities

### ISSUE THREAD

**Issue by KeenthemesHub** [riktar/jkanban#96]
Hi,

Thanks for a great plugin. We want to report, there is an issue with the npm audit.

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ dot-prop                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.1.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jkanban                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jkanban > npm-watch > nodemon > update-notifier >            │
│               │ configstore > dot-prop                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1213                        │
└───────────────┴──────────────────────────────────────────────────────────────┘

Thanks

**Comment by riktar** [comment]
fixed in v1.2.3
